name: RockPaperScissors
version: ${project.version}
main: com.justinmtech.rockpaperscissors.RockPaperScissors
api-version: 1.16
authors: [ Justin ]
description: A Minecraft plugin for playing "rock paper scissors".
website: https://github.com/justinmtech
commands:
  rps:
    description:
    usage: /<command>
  rock:
    description:
    usage: /<command>
  paper:
    description:
    usage: /<command>
  scissors:
    description:
    usage: /<command>

