name: RockPaperScissors
version: ${project.version}
main: com.justinmtech.rockpaperscissors.RockPaperScissors
api-version: 1.16
authors: [ Justin ]
description: A Minecraft plugin for playing "rock paper scissors".
website: https://github.com/justinmtech
commands:
  rps:
    description: Main command
    usage: /rps [accept|<player>] [betAmount]

