name: RockPaperScissors
version: ${project.version}
main: com.justinmtech.rockpaperscissors.RockPaperScissors
api-version: 1.16
author: [JustinMTech]
description: A Minecraft plugin for playing "rock paper scissors".
website: https://github.com/justinmtech
commands:
  rps:
    usage: /<command>
  rock:
    usage: /<command>
  paper:
    usage: /<command>
  scissors:
    usage: /<command>

depend: [Vault]

